alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
functions:
- github:
    branch: main
    deploy_on_push: true
    repo: ihuro/random-ips-do-function
  name: randomips
  routes:
  - path: /
  source_dir: /
name: randomips